### ISSUE TITLE
Plz write a tutorial how can i run this application 

### ISSUE THREAD

**Issue by smamran** [ashikcse20/ASP-MVC5-MULTI-TENANT-REPOSITORY#2]
Plz write a tutorial how can i run this application

**Comment by ashikcse20** [comment]
@smamran 
Please see the  [ README.md](https://github.com/ashikcse20/ASP-MVC5-MULTI-TENANT-REPOSITORY/blob/master/README.md). There is written tutorial as well as video tutorial.
